version: '3'

services:
  app:
    container_name: ${CONTAINER_NAME}
    restart: unless-stopped
    build: ./docker
    image: blog-dev
    volumes:
      - ${PWD}/www:/var/www
    env_file:
      - .env

  mysql:
    container_name:  ${CONTAINER_MYSQL}
    restart: unless-stopped
    image: mariadb
    env_file:
      - .env

networks: 
  default:
    external:
      name: webproxy
