#!/usr/bin/env php
<?php declare(strict_types=1);

if(php_sapi_name()!= "cli")
{
  fwrite(STDERR,
  PHP_EOL."Fichier uniquement pour ligne de commande".PHP_EOL);
  die(1);
}

$demo = false;
foreach($argv as $value)
{
  if($value === "--demo")
  {
    $demo = true;
  }
  if($value === "-h" || $value === "--help")
  {
    echo PHP_EOL."Pour insérer les données de demo utilisez le flag --demo".PHP_EOL;
    exit();
  }
}

require_once '/var/www/vendor/autoload.php';

$dbname = getenv('MYSQL_DATABASE');
$dbuser = getenv('MYSQL_USER');
$dbpassword = getenv('MYSQL_PASSWORD');
$dbcontainer = getenv('CONTAINER_MYSQL');

$pdo = new PDO("mysql:host=$dbcontainer;dbname=$dbname", $dbuser, $dbpassword);

/**
* Suppression de table
*/ 
$pdo->exec('SET FOREIGN_KEY_CHECKS = 0');

$pdo->exec('DROP TABLE supplier');
$pdo->exec('DROP TABLE product');
$pdo->exec('DROP TABLE product_warehouse');
$pdo->exec('DROP TABLE warehouse');
$pdo->exec('DROP TABLE city');
$pdo->exec('DROP TABLE role');
$pdo->exec('DROP TABLE user');

$pdo->exec('SET FOREIGN_KEY_CHECKS = 1');

/**
 * creation tables
 * 
 */

echo "[";
$etape = $pdo->exec("CREATE TABLE supplier(
            `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
            `social` VARCHAR(255) NOT NULL,
            `address` VARCHAR(255) NOT NULL,
            `user_id` INT UNSIGNED NOT NULL,
            PRIMARY KEY(id)
        )");
echo "||";

$etape = $pdo->exec("CREATE TABLE product(
            `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
            `name` VARCHAR(255) NOT NULL,
            `supplier_id` INT UNSIGNED NOT NULL,
            `toxicity` tinyint(1) NOT NULL DEFAULT 0,
            `volume` FLOAT NOT NULL,
            PRIMARY KEY(id)
        )");
echo "||";

$pdo->exec("CREATE TABLE product_warehouse(
            product_id INT UNSIGNED NOT NULL,
            warehouse_id INT UNSIGNED NOT NULL
        )");
echo "||";

$pdo->exec("CREATE TABLE `warehouse` (
    `id` int(11) NOT NULL AUTO_INCREMENT,
    `name` varchar(255) NOT NULL,
    `city_id` INT NOT NULL,
    `surface` FLOAT NOT NULL,
    `address` varchar(255) NOT NULL,
    `user_id` INT UNSIGNED NOT NULL,
    PRIMARY KEY(id)
  )");
echo "||";

$pdo->exec("CREATE TABLE city(
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY(id)
)");
echo "||";

$pdo->exec("CREATE TABLE user(
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `mail` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `role` INT UNSIGNED NOT NULL,
  PRIMARY KEY(id)
)");
echo "||";

$pdo->exec("CREATE TABLE `role`(
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `status` VARCHAR(255) NOT NULL,
  PRIMARY KEY(id)
)");

echo "||||||||||||]
";

echo "Insertion BDD
";

  $villes = ['Marseille', 'Paris', 'Bordeaux', 'Lyon', 'Rennes', 'Nantes', 'Montpellier', 'Nice', 'Clermont-Ferrand', 'Strasbourg', 'Toulouse', 'Lille', 'Brest', 'Reims', 'Perpignan', 'Aurillac', 'Metz', 'Amiens', 'Montluçon', 'Aix-en-Provence'];

  for ($i=0; $i < count($villes) ; $i++) { 
    $pdo->exec("INSERT INTO `city` SET `name` = '$villes[$i]'");
  }

  $pdo->exec("INSERT INTO `role` SET `status` = 'Fournisseur'"); 
  $pdo->exec("INSERT INTO `role` SET `status` = 'Gérant d\'entrepôt'"); 

echo "Insertion BDD terminée
";